// const month = 1
// switch (month) {
//     case 1:
//         console.log("jan");
//         break; 
//     case 2:
//         console.log("feb");
//         break;
//     case 3:
//         console.log("mar");
//         break;

//     default:
//         console.log("default case match");
//         break;
// }

const month = "feb"
switch (month) {
    case "jann":
        console.log("jan");
        break; 
    case "feb":
        console.log("feb");
        break;
    case "maar":
        console.log("mar");
        break;

    default:
        console.log("default case match");
        break;
}

